package com.warren.projecteuler;

public class Problem2 {
    /**
     * Problem Description : Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     * By starting with 1 and 2, the first 10 terms will be:
     * <p>
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * <p>
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms.
     */
    public static void sumOfEvenValuedFibonacciTerms(int firstTerm, int secondTerm, int maximumTermsValue) {
        int result = 0;
        int followingTerm;
        while (firstTerm <= maximumTermsValue) {
            if (firstTerm % 2 == 0) {
                result += firstTerm;
            }
            followingTerm = firstTerm + secondTerm;
            firstTerm = secondTerm;
            secondTerm = followingTerm;

        }

        System.out.println("Problem 2 : By considering the terms in the Fibonacci sequence starting with " + firstTerm +
                " And " + secondTerm + " whose values do not exceed " + maximumTermsValue + ", the sum of the even-valued terms is : " + result);
        System.out.println("***********************************************");
    }
}
